version: '1.0.{build}'
skip_tags: true

image:
  - Ubuntu

install:
  - sh: sudo apt-get update -y
  - sh: sudo apt-get install texlive-lang-all texlive-latex-extra texlive-xetex -y

build_script:
  - sh: xelatex fei.tex
  - sh: xelatex fei.tex
  - sh: xelatex fei.tex

artifacts:
  - path: fei.pdf
    name: fei

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: x2VCjhjls6MUIYqj+WN0D5Db4HA3hTIep++8jGWbSQtnGcPMfzj5gWW39ZNg1z/5
  artifact: fei.pdf
  force_update: true
  draft: false
  prerelease: false
  appveyor_repo_tag: false
