
name: Build LaTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Edit TeX file
      run: |
        sed -i 's/usepackage{longtable}/usepackage{longtable}[=v4.13]/' fei.tex

    - name: Build LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: fei.tex
        latexmk_use_xelatex: true

    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: false
        files: |
          fei.pdf

    - name: Cleanup histories
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 30
        keep_minimum_runs: 0
